name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check TypeScript
        run: bun run typescript:check
        
      - name: Run ESLint
        run: bun run lint

      - name: Check Prettier formatting
        run: bun run format:check

      - name: Type check
        run: bun run tsc

      - name: Run Tests
        run: bun test 